name: Trabajos Independientes

on:
  push:
    branches:
      - main9
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecuci√≥n de la configuracion
        run: sh ./setup_server.sh
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecucionn de la compilacion
        run: sh ./build_server.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out del repositorio
        uses: actions/checkout@v2    
      - name: Ejecucion de las pruebas
        run: sh ./test_server.sh
    
